apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - watch
- apiGroups:
  - eks.cattle.io
  resources:
  - eksclusterconfigs
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - eks.cattle.io
  resources:
  - eksclusterconfigs/status
  verbs:
  - update
